language: java
os: linux
jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2

before_install:
  - sudo apt-get update
  - sudo apt-get install ivy -y

install:
  - ant ivy-bootstrap

script:
  - ant test