language: java
os:
  - linux
  - osx

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9

cache:
  directories:
    - $HOME/.ivy2

before_install:
  - sudo apt-get update
  - sudo apt-get install ivy -y
  - sudo ln -s -T /usr/share/java/ivy.jar /usr/share/ant/lib/ivy*.jar

install:
  - ant ivy-bootstrap

script:
  - ant test